source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TWGOperations_Example' do
  pod "TWGOperations", :path => "../"

  target 'TWGOperations_Tests' do
    pod 'Expecta'
    pod 'OCMock'
  end

  target 'TWGOperations_Integration_Tests' do
    pod 'Expecta'
    pod 'OCMock'
  end

  target 'TWGOperations_Performance_Tests' do
    pod 'Expecta'
    pod 'OCMock'
  end

end
